-- Insertion des catégories
INSERT INTO Categorie (Nom) VALUES ('Axe Compétences'), ('Axe Réactivité'), ('Axe Numérique');

-- Insertion des sous-catégories
INSERT INTO Sous_categorie (Nom, Description, Categorield) VALUES
    ('Excellence Technique/Communauté de pratiques', 'Mesure de l\'excellence technique de l\'entreprise et de la capacité à partager les compétences.', 1),
    ('Faire agile', 'Mesure de l\'adoption d\'une culture agile et d\'une méthodologie agile dans l\'entreprise.', 1),
    ('Gestion humaine des compétences', 'Mesure de la manière dont l\'entreprise gère les compétences de ses collaborateurs.', 1),
    ('Vélocité de réponse', 'Mesure de la capacité de l\'entreprise à répondre rapidement aux besoins du marché et à s\'adapter aux changements.', 2),
    ('Environnements souples', 'Mesure de la capacité de l\'entreprise à s\'adapter aux changements et à fonctionner efficacement dans un environnement changeant.', 2),
    ('Défi environnemental', 'Mesure de l\'engagement de l\'entreprise en matière de développement durable et de réduction de son impact environnemental.', 2),
    ('Veille et benchmark', 'Mesure de la capacité de l\'entreprise à anticiper les tendances du marché et à s\'adapter aux innovations.', 2),
    ('Business model', 'Mesure de la capacité de l\'entreprise à tirer parti du numérique pour améliorer son modèle économique.', 3),
    ('Relation client', 'Mesure de la capacité de l\'entreprise à utiliser le numérique pour améliorer sa relation client et son expérience client.', 3),
    ('Management', 'Mesure de la capacité de l\'entreprise à s\'adapter à l\'évolution du numérique et à gérer les changements liés à la transition numérique.', 3);


-- Insertion des questions
-- Insertion des questions pour Axe Compétences
INSERT INTO Question (Intitule, Reponse0, Reponse1, Reponse2, SousCategorield) VALUES 
    ('Formations pour Apprendre à apprendre, changement de paradigme, "être à la page" (au delà des compétences "justes" nécessaires)', 'Désintérêt pour l\'amélioration de la compétence des équipes', 'Nombreuses formations métiers dans le plan de formation', 'Possibilité de choisir et de suivre des formations "annexes" au métier et/ou temps dédié pour de l\'auto formation', 1),
    ('Le co développement (outill d\'intelligence collective) existe til dans l\'entreprise?', 'Pas du tout', 'Quelques initiatives', 'Démarche instaurée et pratiquée régulièrement', 1),
    ('Les collaborateurs t-ils amenés à partager leurs compétences et sous quelles formes?', 'Aucune initiative', 'Capitalisation d\'ur certain nombre de savoirs', 'Véritable communauté de pratiques en place', 1),
    ('Le mentoring (fonctionnement en binôme) existe til pour assurer le transfert de compétences?', 'Aucune initiative', 'Quelques Initiatives', 'Systématiquement lors d\'une prise de poste', 1),
    ('Les managers sont-ils aussi formateurs sur certains sujet pour l\'entreprise entière?', 'Non', 'Quelques fois', 'Quasi systématiquement', 1),
    ('L\'entreprise favorise t-elle l\'excellence technique ? (Principe 9 du Manifeste Agile)', 'Non', 'Oul un peu', 'Oul', 1),
    ('Déployez vous les pratiques du "Faire Agile", c\'est à dire une ou plusieurs des "méthodes" agiles?', 'NON, nous les projets sont tous en cyde en V/cascade', 'Quelques projets pilotes', 'Déploiement systématique d\'une ou plusieurs méthodes', 2),
    ('Votre entreprise promeut elle un "état d\'esprit agile"?', 'Non', 'Quelques valeurs agiles promues', 'Oul', 2),
    ('Votre entreprise gère t-elle humainement les compétences?', 'Non', 'Un peu', 'Oul', 3);

-- Insertion des questions pour Axe Réactivité
INSERT INTO Question (Intitule, Reponse0, Reponse1, Reponse2, SousCategorield) VALUES 
    ('Valeur supérieure utilisable livrée plus tôt (Fonction principale utilisable dès les premières versions)', 'Pas de phase de validation intermédiaire', 'Prototype fonctionnel intermédiaire livré au client', 'Principe du MVP respecté : Minimum Viable Product/la version d\'un produit qui permet d\'obtenir un maximum de retours client avec un minimum d\'effort', 4),
    ('Réactivité face aux impératifs prépondérants', 'Pas de modification possible en cours de conception', 'Modifications en cours de conception engendrant alors du retard', 'L\'équipe de conception s\'adapte en cas de modification en cours de conception', 4),
    ('Mesure de la vélocité de l\'équipe (indicateur de suivi du travail d\'une équipe de conception)', 'Jamais', 'Suivi des tâches', 'Mesure de la vélocité', 4),
    ('Les installations techniques et de gestion sont modernes (TIC/ERP/CRM)', 'Jamais', 'On laisse la possibilité de créer quelques macros Excel/VBA', 'L\'entreprise équipe et forme ses équipes à la création de site web ou app via des outils no-code', 5),
    ('Les équipes sont en capacité d\'autonomiser une partie de leurs tâches', 'Pas de démarche Agile/Lean initiée dans l\'entreprise', 'Plusieurs concepts Agile/Lean sont mis en œuvre dans l\'entreprise', 'Les concepts Agile/Lean sont inscrits dans l\'ADN de l\'entreprise: Satisfaction du client avec des livraisons au plutôt et régulières, accepter les changements, lisser les activités, collaboration quotidienne avec les parties prenantes, proximité terrain, autonomie des équipes dans la résolution de problèmes, amélioration continue...', 5),
    ('Les équipes s\'inscrivent dans un cadre Agile Lean', 'Pas de démarche de tension des flux', 'Quelques concepts du juste à temps sont mis en œuvre pour tendre le flux', 'Concepts du juste à temps maîtrisés (production rythmée par la demande client, peu d\'en-cours)', 5),
    ('Les mécanismes de livraison et de synchronisation sont matures', 'Auxune réflexion sur cet axe', 'Des premières initiatives ont été lancées', 'Systématiquement', 6),
    ('Les innovations produit tiennent compte de l\'urgence climatique', 'Auxune réflexion sur cet axe', 'Des premières initiatives ont été lancées', 'Systématiquement', 6),
    ('Les processus internes sont remis en cause pour diminuer leur impact environnemental', 'Auxune réflexion sur cet axe', 'Des premières initiatives ont été lancées', 'Systématiquement', 6),
    ('Les parties prenantes sont sélectionnées en fonction de leur éthique vis-à-vis du développement durable', 'Pas de veille', 'La veille stratégique de l\'entreprise permet d\'anticiper les évolutions et les innovations', 'La veille stratégique de l\'entreprise permet d\'anticiper les disruptions nécessaires', 6),
    ('Veille stratégique', 'Pas de veille', 'La veille stratégique de l\'entreprise permet d\'anticiper les évolutions et les innovations', 'La veille stratégique de l\'entreprise permet d\'anticiper les disruptions nécessaires', 7);


-- Insertion des questions pour Axe Numérique
INSERT INTO Question (Intitule, Reponse0, Reponse1, Reponse2, SousCategorield) VALUES 
	('Votre entreprise dégage t-elle une part de CA par des produits ou services en ligne?', 'Moins de 10%', 'Oui environ 20%', 'Oui environ 30%', 8),
	('La mise en place d''outils numériques a-t-elle permis d''optimiser les coûts, les délais et la qualité ?', 'Aucun', 'Oui mais pas pour tous les critères', 'Oui pour tous les critères', 8),
	('Comment les outils sont-ils intégrés dans les process de l''entreprise ?', 'En mode novice: au mieux par mail ou via le site internet', 'En mode collaboratif: quelques aménagements (type sharepoint, drive) pour des sujets plutôt ponctuels', 'En mode avancé: des plateformes dédiées (type extranet, applications) sont intégrées au mode de partage permanent', 8),
	('Comment partagez-vous les données numériques avec les parties prenantes (clients, fournisseurs,...)?', 'Non', 'Oui et non on observe sans mesurer', 'Oui des outils de mesure sont en place', 8),
	('Mesurez-vous les impacts du numérique sur votre entreprise ?', 'Non', 'C''est un sujet observé de loin, on traite les questions d''obligation légales sans aller plus loin', 'Le numérique est un sujet totalement rattaché à la démarche RSE', 8),
	('Quel est l''impact du numérique sur la démarche RSE de l''entreprise ?', 'Absence de démarche RSE', 'Oui l''entreprise est plutôt frileuse, on ne dépense que le strict nécessaire pour que les outils fonctionnent sans recherche de performance', 'Non des budgets sont alloués et l''entreprise a bien compris cette nécessité dans sa stratégie', 8),
	('Existe-t-il des freins (stratégiques, financiers,...) à l''investissement dans les outils numériques?', 'Oui la statégie de l''entreprise n''est pas orientée en faveur du numérique, elle n''investit pas', 'Oui mais seulement sur le site internet = 1 point', 'Oui la présence de l''entreprise sur les réseaux est visible, elle correspond au secteur d''activité', 8),
	('L''entreprise dispose-t-elle: d''un site internet, d''un compte Linkedin, d''une page Facebook, d''un compte Twitter,...?', 'Non le site/la page réseau sont inexistants ou inactifs', 'Oui mais seulement sur le site internet', 'Plusieurs modes d''utilisation sont possibles pour échanger avec l''exterme, ils sont performants et adaptés avec l''activité de l''entreprise', 9),
	('Comment utilisez-vous le numérique dans la relation client? (nouveau modèle de vente, nouveau modèle d''échanges avec les clients, communauté, story, chat,...)', 'Absence de plateforme de contact', 'Non mais une personne se charge de l''animation des réseaux sociaux parmi ses autres tâches', 'Oui avec des incitations de l''entreprise pour le faire', 9),
	('L''entreprise dispose-t-elle d''un community manager?', 'Non ou rarement', 'Oui sans incitation', 'Oui', 9),
	('Certains de vos collaborateurs sont-ils actifs sur les réseaux sociaux au nom de l''entreprise ?', 'Absence de suivi', 'Des indicateurs sont en place mais plutôt de façon passive, ils servent à mesurer', 'Des indicateurs sont mis en place afin de mesurer l''efficacité et l''impact du site sur les réseaux, une recherche de performance est en place pour toucher toujours plus et mieux', 9),
	('Comment mesurez-vous et exploitez-vous les données issues du site de votre entreprise ?', 'Oui ils sont tellement performants et en avance que nous pourrions perdre des marchés', 'Oui ils ont quelques belles idées, si seulement on pouvait faire aussi bien qu''eux', 'Oui elles servent comme base de reflexion et de développement pour notre propre entreprise. On peut être rivaliser!', 9),
	('Avez-vous observé chez vos concurrents des pratiques innovantes?', 'Oui ils sont tellement performants et en avance que nous pourrions perdre des marchés', 'Oui ils ont quelques belles idées, si seulement on pouvait faire aussi bien qu\'eux', 'Oui elles servent comme base de reflexion et de développement pour notre propre entreprise. On peut être rivaliser !', 9),
	('Vos collaborateurs sont-ils équipés de nouveaux équipements numériques de travail (PC portable, tablette, smartphone,...)?', 'Les fonctions supports ne sont pas amenées à être équipé pour le travail à distance. L\'entreprise fonctionne majoritairement sur le mode papier.', 'Les processus s\'appuient rarement sur la numérisation des données et les outils numériques. Le potentiel ne semble pas pleinement exploité.', 'Les processus de travail s\'appuient sur des outils numériques quand ceux-ci sont possibles. L\'ensemble des fonctions de l\'entreprise sont équipées pour pouvoir réaliser le travail à distance quand celui-ci est possible', 10),
	('L''arrivée des outils digitaux a-t-elle eu un impact sur les pratiques et la culture de l''entreprise?', 'Non au contraire, peu de monde y adhère', 'Oui dans l\'ensemble toutefois nous rencontrons parfois des contraintes (pratiques, techniques,…)', 'Oui gain de temps, facilité, économies et fiabilité', 10),
	('Comment vous êtes-vous approprié et comment avez-vous accompagné ces évolutions?', 'Absence de communication et d\'accompagnement', ' La communication n\'est pas parfaite, les personnes qui peuvent se sentir en difficultés avec les nouvelles pratiques ne sont pas forcémment considérées.', 'Tout est en place pour faciliter la compréhension et l\'adhésion aux nouveaux outils/pratiques', 10),
	('Les nouvelles possibilités technologiques ont-elles fait évoluer le modèle d''organisation de l''entreprise et/ou votre management, vers plus de collaboration avec des acteurs internes ou externes?', 'L\'organisation est en silot, absence de projets transversaux et d\'interactions avec les autres sites', 'Oui quelques évolutions s\'opèrent pour travailler en inter-service ou avec l\'externe, toutefois le potentiel n\'est pas pleinement exploité', 'Oui on sort complétement du mode silot et on favorise le mode projet', 10),
	('Mobilisez-vous des outils de veille et mettez-vous en œuvre des modalités de curation et de partage de l''information?', 'Absence de veille', 'Il y a un peu de benchmark toutefois les décisions d\'évolutions sont un peu tardive (quand il n y a plus le choix)', 'Oui l\'entreprise est en capacité de mesurer sa performance et de réagir rapidement pour se mettre à jour', 10),
	('Les fonctionnalités des outils sont-elles augmentées par la pratique de vos collaborateurs ?', 'Absence de prise en compte des pratiques terrain', 'Oui mais les outils sont vieillissants, il y a des freins pour les faire évoluer', 'Oui totalement les outils s\'adaptent au terrain quotidiennement', 10),
	('Comment accompagnez-vous vos collaborateurs dans la transition numérique ?', 'Absence d\'accompagnement', 'L\'entreprise accompagne en faisant de son mieux pour faire adhérer les autres, il y a parfois quelques blocages. J\'aimerais parfois être moi-même accompagné', 'L\'entreprise est pro-active par la promotion des innovations et des outils numériques. J\'adgère', 10);